#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Mar 10, 2019 06:35:54 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import excelator_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = _Excel_ator_by_Naga_Sai_Nikhil (root)
    excelator_support.init(root, top)
    root.mainloop()

w = None
def create__Excel_ator_by_Naga_Sai_Nikhil(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = _Excel_ator_by_Naga_Sai_Nikhil (w)
    excelator_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy__Excel_ator_by_Naga_Sai_Nikhil():
    global w
    w.destroy()
    w = None


class _Excel_ator_by_Naga_Sai_Nikhil:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1227x815+332+109")
        top.title("'Excel'ator by Naga Sai Nikhil")
        top.configure(background="#cdd886")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.path = ttk.Entry(top)
        self.path.place(relx=0.1, rely=0.06, relheight=0.03, relwidth=0.2)
        self.path.configure(takefocus="")
        self.path.configure(cursor="ibeam")

        self.Label1 = Label(top)
        self.Label1.place(relx=0.01, rely=0.06, height=23, width=102)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#cdd886")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Enter File Path''')

        self.loadworkbook = ttk.Button(top)
        self.loadworkbook.place(relx=0.11, rely=0.12, height=47, width=152)
        self.loadworkbook.configure(command=excelator_support.loadexcel)
        self.loadworkbook.configure(takefocus="")
        self.loadworkbook.configure(text='''Load Workbook''')

        self.TLabel2 = ttk.Label(top)
        self.TLabel2.place(relx=0.02, rely=0.93, height=41, width=1135)
        self.TLabel2.configure(background="#cdd886")
        self.TLabel2.configure(foreground="#000000")
        self.TLabel2.configure(font="TkDefaultFont")
        self.TLabel2.configure(relief=FLAT)
        self.TLabel2.configure(text='''Unloaded''')

        self.TLabel3 = ttk.Label(top)
        self.TLabel3.place(relx=0.03, rely=0.22, height=21, width=112)
        self.TLabel3.configure(background="#cdd886")
        self.TLabel3.configure(foreground="#000000")
        self.TLabel3.configure(font="TkDefaultFont")
        self.TLabel3.configure(relief=FLAT)
        self.TLabel3.configure(text='''Search for Value''')

        self.TEntry1 = ttk.Entry(top)
        self.TEntry1.place(relx=0.02, rely=0.27, relheight=0.03, relwidth=0.14)
        self.TEntry1.configure(takefocus="")
        self.TEntry1.configure(cursor="ibeam")

        self.getentirerow = ttk.Button(top)
        self.getentirerow.place(relx=0.03, rely=0.32, height=27, width=109)
        self.getentirerow.configure(command=excelator_support.getfullrow)
        self.getentirerow.configure(takefocus="")
        self.getentirerow.configure(text='''Get Entire Row''')

        self.Label2 = Label(top)
        self.Label2.place(relx=0.04, rely=0.36, height=33, width=71)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#cdd886")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''OR''')

        self.cols = ttk.Entry(top)
        self.cols.place(relx=0.02, rely=0.4, relheight=0.03, relwidth=0.14)
        self.cols.configure(takefocus="")
        self.cols.configure(cursor="ibeam")

        self.TButton2 = ttk.Button(top)
        self.TButton2.place(relx=0.02, rely=0.45, height=27, width=160)
        self.TButton2.configure(command=excelator_support.getspecifiedcols)
        self.TButton2.configure(takefocus="")
        self.TButton2.configure(text='''Get Specified Columns''')

        self.TLabel4 = ttk.Label(top)
        self.TLabel4.place(relx=0.29, rely=0.22, height=21, width=85)
        self.TLabel4.configure(background="#cdd886")
        self.TLabel4.configure(foreground="#000000")
        self.TLabel4.configure(font="TkDefaultFont")
        self.TLabel4.configure(relief=FLAT)
        self.TLabel4.configure(text='''Modify Value''')

        self.TLabel5 = ttk.Label(top)
        self.TLabel5.place(relx=0.21, rely=0.27, height=21, width=27)
        self.TLabel5.configure(background="#cdd886")
        self.TLabel5.configure(foreground="#000000")
        self.TLabel5.configure(font="TkDefaultFont")
        self.TLabel5.configure(relief=FLAT)
        self.TLabel5.configure(text='''old:''')

        self.old = ttk.Entry(top)
        self.old.place(relx=0.24, rely=0.27, relheight=0.03, relwidth=0.15)
        self.old.configure(takefocus="")
        self.old.configure(cursor="ibeam")

        self.TLabel6 = ttk.Label(top)
        self.TLabel6.place(relx=0.2, rely=0.32, height=21, width=35)
        self.TLabel6.configure(background="#cdd886")
        self.TLabel6.configure(foreground="#000000")
        self.TLabel6.configure(font="TkDefaultFont")
        self.TLabel6.configure(relief=FLAT)
        self.TLabel6.configure(text='''new:''')

        self.new = ttk.Entry(top)
        self.new.place(relx=0.24, rely=0.32, relheight=0.03, relwidth=0.15)
        self.new.configure(takefocus="")
        self.new.configure(cursor="ibeam")

        self.TButton3 = ttk.Button(top)
        self.TButton3.place(relx=0.26, rely=0.37, height=37, width=118)
        self.TButton3.configure(command=excelator_support.modifyvalue)
        self.TButton3.configure(takefocus="")
        self.TButton3.configure(text='''Modify''')

        self.TButton4 = ttk.Button(top)
        self.TButton4.place(relx=0.35, rely=0.04, height=57, width=168)
        self.TButton4.configure(command=excelator_support.reverse_cols)
        self.TButton4.configure(takefocus="")
        self.TButton4.configure(text='''Reverse Columns''')

        self.TLabel7 = ttk.Label(top)
        self.TLabel7.place(relx=0.06, rely=0.55, height=31, width=81)
        self.TLabel7.configure(background="#cdd886")
        self.TLabel7.configure(foreground="#000000")
        self.TLabel7.configure(font="TkDefaultFont")
        self.TLabel7.configure(relief=FLAT)
        self.TLabel7.configure(text='''Merge Cells''')

        self.TLabel8 = ttk.Label(top)
        self.TLabel8.place(relx=0.02, rely=0.63, height=21, width=84)
        self.TLabel8.configure(background="#cdd886")
        self.TLabel8.configure(foreground="#000000")
        self.TLabel8.configure(font="TkDefaultFont")
        self.TLabel8.configure(relief=FLAT)
        self.TLabel8.configure(text='''starting row:''')

        self.startrow = ttk.Entry(top)
        self.startrow.place(relx=0.09, rely=0.63, relheight=0.03, relwidth=0.08)
        self.startrow.configure(takefocus="")
        self.startrow.configure(cursor="ibeam")

        self.TLabel9 = ttk.Label(top)
        self.TLabel9.place(relx=0.02, rely=0.69, height=21, width=79)
        self.TLabel9.configure(background="#cdd886")
        self.TLabel9.configure(foreground="#000000")
        self.TLabel9.configure(font="TkDefaultFont")
        self.TLabel9.configure(relief=FLAT)
        self.TLabel9.configure(text='''ending row:''')

        self.endrow = ttk.Entry(top)
        self.endrow.place(relx=0.09, rely=0.69, relheight=0.03, relwidth=0.08)
        self.endrow.configure(takefocus="")
        self.endrow.configure(cursor="ibeam")

        self.TLabel10 = ttk.Label(top)
        self.TLabel10.place(relx=0.01, rely=0.75, height=21, width=108)
        self.TLabel10.configure(background="#cdd886")
        self.TLabel10.configure(foreground="#000000")
        self.TLabel10.configure(font="TkDefaultFont")
        self.TLabel10.configure(relief=FLAT)
        self.TLabel10.configure(text='''starting column:''')

        self.startcolumn = ttk.Entry(top)
        self.startcolumn.place(relx=0.1, rely=0.75, relheight=0.03
                , relwidth=0.08)
        self.startcolumn.configure(takefocus="")
        self.startcolumn.configure(cursor="ibeam")

        self.TLabel11 = ttk.Label(top)
        self.TLabel11.place(relx=0.01, rely=0.8, height=21, width=103)
        self.TLabel11.configure(background="#cdd886")
        self.TLabel11.configure(foreground="#000000")
        self.TLabel11.configure(font="TkDefaultFont")
        self.TLabel11.configure(relief=FLAT)
        self.TLabel11.configure(text='''ending column:''')

        self.endcolumn = ttk.Entry(top)
        self.endcolumn.place(relx=0.1, rely=0.8, relheight=0.03, relwidth=0.08)
        self.endcolumn.configure(takefocus="")
        self.endcolumn.configure(cursor="ibeam")

        self.TButton5 = ttk.Button(top)
        self.TButton5.place(relx=0.04, rely=0.85, height=37, width=108)
        self.TButton5.configure(command=excelator_support.mergecells)
        self.TButton5.configure(takefocus="")
        self.TButton5.configure(text='''Merge''')

        self.Label3 = Label(top)
        self.Label3.place(relx=0.46, rely=0.22, height=23, width=156)
        self.Label3.configure(background="#cdd886")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Set Active Sheet Name''')

        self.Label4 = Label(top)
        self.Label4.place(relx=0.42, rely=0.27, height=23, width=49)
        self.Label4.configure(background="#cdd886")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''Name:''')

        self.activesheetname = ttk.Entry(top)
        self.activesheetname.place(relx=0.47, rely=0.27, relheight=0.03
                , relwidth=0.14)
        self.activesheetname.configure(takefocus="")
        self.activesheetname.configure(cursor="ibeam")

        self.TButton1 = ttk.Button(top)
        self.TButton1.place(relx=0.49, rely=0.32, height=27, width=98)
        self.TButton1.configure(command=excelator_support.setactivesheetname)
        self.TButton1.configure(takefocus="")
        self.TButton1.configure(text='''Set''')

        self.TLabel12 = ttk.Label(top)
        self.TLabel12.place(relx=0.3, rely=0.55, height=21, width=84)
        self.TLabel12.configure(background="#cdd886")
        self.TLabel12.configure(foreground="#000000")
        self.TLabel12.configure(font="TkDefaultFont")
        self.TLabel12.configure(relief=FLAT)
        self.TLabel12.configure(text='''Insert Image''')

        self.TLabel13 = ttk.Label(top)
        self.TLabel13.place(relx=0.2, rely=0.63, height=21, width=88)
        self.TLabel13.configure(background="#cdd886")
        self.TLabel13.configure(foreground="#000000")
        self.TLabel13.configure(font="TkDefaultFont")
        self.TLabel13.configure(relief=FLAT)
        self.TLabel13.configure(text='''Image path :''')

        self.imagepath = ttk.Entry(top)
        self.imagepath.place(relx=0.28, rely=0.63, relheight=0.03, relwidth=0.14)

        self.imagepath.configure(width=166)
        self.imagepath.configure(takefocus="")
        self.imagepath.configure(cursor="ibeam")

        self.TLabel14 = ttk.Label(top)
        self.TLabel14.place(relx=0.22, rely=0.67, height=21, width=50)
        self.TLabel14.configure(background="#cdd886")
        self.TLabel14.configure(foreground="#000000")
        self.TLabel14.configure(font="TkDefaultFont")
        self.TLabel14.configure(relief=FLAT)
        self.TLabel14.configure(text='''at cell :''')

        self.atcell = ttk.Entry(top)
        self.atcell.place(relx=0.28, rely=0.67, relheight=0.03, relwidth=0.14)
        self.atcell.configure(takefocus="")
        self.atcell.configure(cursor="ibeam")

        self.TButton6 = ttk.Button(top)
        self.TButton6.place(relx=0.27, rely=0.74, height=47, width=128)
        self.TButton6.configure(command=excelator_support.insertimage)
        self.TButton6.configure(takefocus="")
        self.TButton6.configure(text='''Insert''')
        self.TButton6.configure(width=128)

        self.TLabel15 = ttk.Label(top)
        self.TLabel15.place(relx=0.53, rely=0.55, height=21, width=63)
        self.TLabel15.configure(background="#cdd886")
        self.TLabel15.configure(foreground="#000000")
        self.TLabel15.configure(font="TkDefaultFont")
        self.TLabel15.configure(relief=FLAT)
        self.TLabel15.configure(text='''Set Font''')

        self.TLabel16 = ttk.Label(top)
        self.TLabel16.place(relx=0.45, rely=0.63, height=21, width=84)
        self.TLabel16.configure(background="#cdd886")
        self.TLabel16.configure(foreground="#000000")
        self.TLabel16.configure(font="TkDefaultFont")
        self.TLabel16.configure(relief=FLAT)
        self.TLabel16.configure(text='''Font Name:''')

        self.fontname = ttk.Entry(top)
        self.fontname.place(relx=0.52, rely=0.63, relheight=0.03, relwidth=0.14)
        self.fontname.configure(takefocus="")
        self.fontname.configure(cursor="ibeam")

        self.TLabel17 = ttk.Label(top)
        self.TLabel17.place(relx=0.45, rely=0.67, height=21, width=74)
        self.TLabel17.configure(background="#cdd886")
        self.TLabel17.configure(foreground="#000000")
        self.TLabel17.configure(font="TkDefaultFont")
        self.TLabel17.configure(relief=FLAT)
        self.TLabel17.configure(text='''Font Size :''')

        self.fontsize = ttk.Entry(top)
        self.fontsize.place(relx=0.52, rely=0.67, relheight=0.03, relwidth=0.14)
        self.fontsize.configure(takefocus="")
        self.fontsize.configure(cursor="ibeam")

        self.TButton7 = ttk.Button(top)
        self.TButton7.place(relx=0.51, rely=0.75, height=47, width=128)
        self.TButton7.configure(command=excelator_support.setfont)
        self.TButton7.configure(takefocus="")
        self.TButton7.configure(text='''Set''')
        self.TButton7.configure(width=128)






if __name__ == '__main__':
    vp_start_gui()


