#############################################################################
# Generated by PAGE version 4.14
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#cdd886} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1227x815+330+122
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "'Excel'ator"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    ttk::entry $top.tEn38 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn38" "path" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#cdd886} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Enter File Path} 
    vTcl:DefineAlias "$top.lab39" "Label1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu40 \
        -command loadexcel -takefocus {} -text {Load Workbook} 
    vTcl:DefineAlias "$top.tBu40" "loadworkbook" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tBu40.tLa41 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text Tlabel 
    vTcl:DefineAlias "$top.tBu40.tLa41" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa43 \
        -background {#cdd886} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text Unloaded 
    vTcl:DefineAlias "$top.tLa43" "TLabel2" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa38 \
        -background {#cdd886} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text {Search for Value} 
    vTcl:DefineAlias "$top.tLa38" "TLabel3" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry $top.tEn39 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn39" "TEntry1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu41 \
        -command getfullrow -takefocus {} -text {Get Entire Row} 
    vTcl:DefineAlias "$top.tBu41" "getentirerow" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab43 \
        -background {#cdd886} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text OR 
    vTcl:DefineAlias "$top.lab43" "Label2" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry $top.tEn44 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn44" "cols" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu45 \
        -command getspecifiedcols -takefocus {} -text {Get Specified Columns} 
    vTcl:DefineAlias "$top.tBu45" "TButton2" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa46 \
        -background {#cdd886} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text {Modify Value} 
    vTcl:DefineAlias "$top.tLa46" "TLabel4" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa47 \
        -background {#cdd886} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text old: 
    vTcl:DefineAlias "$top.tLa47" "TLabel5" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry $top.tEn48 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn48" "old" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa49 \
        -background {#cdd886} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text new: 
    vTcl:DefineAlias "$top.tLa49" "TLabel6" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry $top.tEn50 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn50" "new" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu51 \
        -command modifyvalue -takefocus {} -text Modify 
    vTcl:DefineAlias "$top.tBu51" "TButton3" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu52 \
        -command reverse_cols -takefocus {} -text {Reverse Columns} 
    vTcl:DefineAlias "$top.tBu52" "TButton4" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tEn38 \
        -in $top -x 120 -y 50 -width 246 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab39 \
        -in $top -x 10 -y 50 -anchor nw -bordermode ignore 
    place $top.tBu40 \
        -in $top -x 140 -y 100 -width 152 -relwidth 0 -height 47 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu40.tLa41 \
        -in $top.tBu40 -x -90 -y 640 -anchor nw -bordermode ignore 
    place $top.tLa43 \
        -in $top -x 30 -y 760 -width 1135 -relwidth 0 -height 41 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa38 \
        -in $top -x 40 -y 180 -anchor nw -bordermode ignore 
    place $top.tEn39 \
        -in $top -x 20 -y 220 -anchor nw -bordermode ignore 
    place $top.tBu41 \
        -in $top -x 40 -y 260 -anchor nw -bordermode ignore 
    place $top.lab43 \
        -in $top -x 50 -y 290 -width 71 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tEn44 \
        -in $top -x 20 -y 330 -anchor nw -bordermode ignore 
    place $top.tBu45 \
        -in $top -x 30 -y 370 -anchor nw -bordermode ignore 
    place $top.tLa46 \
        -in $top -x 350 -y 180 -anchor nw -bordermode ignore 
    place $top.tLa47 \
        -in $top -x 260 -y 220 -anchor nw -bordermode ignore 
    place $top.tEn48 \
        -in $top -x 290 -y 220 -width 186 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa49 \
        -in $top -x 250 -y 260 -anchor nw -bordermode ignore 
    place $top.tEn50 \
        -in $top -x 290 -y 260 -width 186 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu51 \
        -in $top -x 320 -y 300 -width 118 -relwidth 0 -height 37 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu52 \
        -in $top -x 430 -y 30 -width 168 -relwidth 0 -height 57 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

